[package]
name = "rust-test-eboot"
version = "0.1.0"
edition = "2024"

[dependencies]
psp = "0.3.12"
bytemuck = { version = "1.23", features = ["derive", "extern_crate_alloc"] }

[profile.dev.package.psp]
opt-level = 3
