[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/rust-test-eboot"]

[workspace.dependencies]
psp = "0.3.12"
psp-gfx = { path = "./crates/psp-gfx" }

[profile.dev.package.psp]
opt-level = 3
