[package]
name = "psp-gfx"
version = "0.1.0"
edition = "2024"

[dependencies]
psp.workspace = true
bytemuck = { version = "1.23", features = ["derive", "extern_crate_alloc"] }

[features]
default = ["gfx_ext"]
gfx_ext = []
